window.NEON_BREW_INITIAL_STATE = Object.freeze({
  create(ingredients) {
    return {
      modernCafeVersion: 6,
      money: 250000,
      reputation: 0,
      served: 0,
      xp: 0,
      level: 1,
      machineLevel: 0,
      bots: 0,
      branches: 1,
      inventory: Object.fromEntries(ingredients.map(item => [item.id, item.start])),
      cyberWaste: 0,
      unlockedRecipes: [],
      researchTrials: 0,
      researchSuccesses: 0,
      researchFailures: 0,
      tutorialStep: 0,
      tutorialDone: false,
      factionRep: { hackers: 0, samurai: 0, corporate: 0, cyborgs: 0 },
      customerLoyalty: { hackers: 0, samurai: 0, corporate: 0, cyborgs: 0 },
      orderFaction: 'hackers',
      orderId: 'meteor',
      orderNumber: 1,
      orderStarted: Date.now(),
      orderExpires: Date.now() + 45000,
      orderVip: false,
      orderShuffleAt: Date.now() + 30000,
      weatherId: 'neon',
      weatherChangedAt: Date.now() + 90000,
      decorations: {},
      drone: 0,
      bouncer: 0,
      firewall: 0,
      deliveryDrone: 0,
      deliveryActive: false,
      robotUnion: false,
      maintenanceDueAt: Date.now() + 3600000,
      matrixCyclesLeft: 0,
      matrixCycleEnds: 0,
      matrixNextAt: Date.now() + 180000,
      yakuzaProtectionUntil: 0,
      bulkOrder: null,
      arenaBuffUntil: 0,
      stalledUntil: 0,
      securityNextAt: Date.now() + 25000,
      securityEvictions: 0,
      ransomwareIncidents: 0,
      tracks: ['afterglow'],
      trackId: 'afterglow',
      audio: false,
      crt: false,
      daily: { date: new Date().toISOString().slice(0, 10), espresso: 0, hackers: 0, seconds: 0, rewarded: false },
      chips: 0,
      prestiges: 0,
      badges: { millionaire: false, recipes: false, rebirth: false },
      lastSeen: Date.now(),
      log: [],
      badOrders: 0,
      reviewScore: 100,
      starRating: 5,
      inspectionProgress: 0,
      inspectionActive: false,
      gameOver: false,
      paranoia: 0,
      ghostOrder: null,
      loreFragments: [],
      lastHorrorAt: Date.now(),
      hallucinationUntil: 0,
      robotWhisper: '',
      horrorPhase: 0,
      combo: 0,
      bestCombo: 0,
      totalOrders: 0,
      perfectOrders: 0,
      failedOrders: 0,
      currentOrder: null,
      statistics: { orders: 0, perfect: 0, failed: 0, bestCombo: 0 }
    };
  }
});